/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  focus?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  headline?: string;
  bio?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "statItem";
    _key: string;
  }>;
  heroChips?: Array<string>;
  socialLinks?: {
    linkedin?: string;
    github?: string;
    whatsapp?: string;
    email?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  degree?: string;
  institution?: string;
  honors?: string;
  gpa?: string;
  period?: string;
  order?: number;
};

export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  order?: number;
  skills?: Array<{
    name?: string;
    isPrimary?: boolean;
    _type: "skillItem";
    _key: string;
  }>;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  role?: string;
  isCurrent?: boolean;
  period?: string;
  location?: string;
  technologies?: Array<string>;
  responsibilities?: Array<string>;
  order?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tagline?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  technologies?: Array<string>;
  siteUrl?: string;
  githubUrl?: string;
  publishedAt?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Profile
  | SanityImageCrop
  | SanityImageHotspot
  | Education
  | SkillCategory
  | Experience
  | Project
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: PORTFOLIO_PAGE_QUERY
// Query: {  "profile": *[_type == "profile"][0]{    _id,    name,    title,    focus,    headline,    bio,    profileImage {      asset,      alt    },    stats[] {      _key,      value,      label    },    heroChips,    socialLinks {      github,      linkedin,      whatsapp,      email    }  },  "projects": *[_type == "project" && defined(slug.current)] | order(coalesce(order, 100) asc, publishedAt desc, _createdAt desc){    _id,    title,    slug,    tagline,    order,    coverImage {      asset,      alt    },    overview,    technologies,    siteUrl,    githubUrl,    publishedAt  },  "experiences": *[_type == "experience"] | order(order asc){    _id,    company,    role,    isCurrent,    period,    location,    technologies,    responsibilities,    order  },  "skills": *[_type == "skillCategory"] | order(order asc){    _id,    title,    order,    skills[] {      _key,      name,      isPrimary    }  },  "education": *[_type == "education"] | order(order asc){    _id,    degree,    institution,    honors,    gpa,    period,    order  }}
export type PORTFOLIO_PAGE_QUERY_RESULT = {
  profile: {
    _id: string;
    name: string | null;
    title: string | null;
    focus: string | null;
    headline: string | null;
    bio: string | null;
    profileImage: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
    stats: Array<{
      _key: string;
      value: string | null;
      label: string | null;
    }> | null;
    heroChips: Array<string> | null;
    socialLinks: {
      github: string | null;
      linkedin: string | null;
      whatsapp: string | null;
      email: string | null;
    } | null;
  } | null;
  projects: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    tagline: string | null;
    order: null;
    coverImage: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
    overview: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    technologies: Array<string> | null;
    siteUrl: string | null;
    githubUrl: string | null;
    publishedAt: string | null;
  }>;
  experiences: Array<{
    _id: string;
    company: string | null;
    role: string | null;
    isCurrent: boolean | null;
    period: string | null;
    location: string | null;
    technologies: Array<string> | null;
    responsibilities: Array<string> | null;
    order: number | null;
  }>;
  skills: Array<{
    _id: string;
    title: string | null;
    order: number | null;
    skills: Array<{
      _key: string;
      name: string | null;
      isPrimary: boolean | null;
    }> | null;
  }>;
  education: Array<{
    _id: string;
    degree: string | null;
    institution: string | null;
    honors: string | null;
    gpa: string | null;
    period: string | null;
    order: number | null;
  }>;
};

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    slug,    tagline,    coverImage {      asset,      alt    },    overview,    technologies,    siteUrl,    githubUrl,    publishedAt  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  tagline: string | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  technologies: Array<string> | null;
  siteUrl: string | null;
  githubUrl: string | null;
  publishedAt: string | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "profile": *[_type == "profile"][0]{\n    _id,\n    name,\n    title,\n    focus,\n    headline,\n    bio,\n    profileImage {\n      asset,\n      alt\n    },\n    stats[] {\n      _key,\n      value,\n      label\n    },\n    heroChips,\n    socialLinks {\n      github,\n      linkedin,\n      whatsapp,\n      email\n    }\n  },\n  "projects": *[_type == "project" && defined(slug.current)] | order(coalesce(order, 100) asc, publishedAt desc, _createdAt desc){\n    _id,\n    title,\n    slug,\n    tagline,\n    order,\n    coverImage {\n      asset,\n      alt\n    },\n    overview,\n    technologies,\n    siteUrl,\n    githubUrl,\n    publishedAt\n  },\n  "experiences": *[_type == "experience"] | order(order asc){\n    _id,\n    company,\n    role,\n    isCurrent,\n    period,\n    location,\n    technologies,\n    responsibilities,\n    order\n  },\n  "skills": *[_type == "skillCategory"] | order(order asc){\n    _id,\n    title,\n    order,\n    skills[] {\n      _key,\n      name,\n      isPrimary\n    }\n  },\n  "education": *[_type == "education"] | order(order asc){\n    _id,\n    degree,\n    institution,\n    honors,\n    gpa,\n    period,\n    order\n  }\n}': PORTFOLIO_PAGE_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    tagline,\n    coverImage {\n      asset,\n      alt\n    },\n    overview,\n    technologies,\n    siteUrl,\n    githubUrl,\n    publishedAt\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
